#დავალება 2: პრინტ ბრძანება 20-ჯერ გამოვიყენოთ და დავბეჭდოთ ჩვენთვის სასურველი ინფორმაცია
print("my fullname is revia aleqandre")
print("Im 15 years old")
print("My birthday is on october first")
print("I currently study at GOA")
print("We got best mentors there")
print("Join to become the ultimate CHAD")
print("I started to study because i wanted to become a better person")
print("we mog")
print("programming on top")
print("python course")
print("do 100 push ups everyday")
print("become a better person")
print("be disciplined")
print("work hard")
print("chase your dreams")
print("dream big")
print("Be a real chad")
print("eat healthy")
print("goodbye")